name: Job workflow

on:
  push:
    branches:
    - 'master'

jobs:
  job1:
    runs-on: Windows
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: compile java code
      run: mvn compile
